title: Das Keyboard 5Q Extras Repo
author: Daniel Lund
email: daniel.lund14@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Please submit your email if you are interested in joining the slack channel, and I will add you

theme: jekyll-theme-slate
